import {
  BrowserWindow,
  app,
  ipcMain,
  desktopCapturer,
  session,
} from "electron";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
import Prism from "prismjs";
import OpenAI from "openai";
import axios from "axios";
import FormData from "form-data";
import fs from "fs";
import path from "path";
import { Buffer } from "buffer";
import { createClient, LiveTranscriptionEvents } from "@deepgram/sdk";

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
import electronSquirrelStartup from "electron-squirrel-startup";

if (electronSquirrelStartup) {
  app.quit();
}

const createWindow = (): void => {
  const isDevelopment = !app.isPackaged;
  const contentSecurityPolicy = isDevelopment
    ? "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self' https: http://localhost:* ws: wss:; object-src 'none'; base-uri 'self'; frame-ancestors 'none';"
    : "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self' https: wss:; object-src 'none'; base-uri 'self'; frame-ancestors 'none';";

  const window = new BrowserWindow({
    height: 1000,
    width: 1300,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      webSecurity: true,
      sandbox: true,
    },
  });

  mainWindow = window;

  window.webContents.session.webRequest.onHeadersReceived(
    (details, callback) => {
      callback({
        responseHeaders: {
          ...details.responseHeaders,
          "Content-Security-Policy": [
            contentSecurityPolicy,
          ],
        },
      });
    }
  );

  window.webContents.session.setPermissionRequestHandler(
    (webContents, permission, callback) => {
      if (permission === "media" && webContents.id === window.webContents.id) {
        callback(true);
      } else {
        callback(false);
      }
    }
  );

  window.webContents.setWindowOpenHandler(() => ({ action: "deny" }));
  window.webContents.on("will-navigate", (event, url) => {
    if (url !== window.webContents.getURL()) {
      event.preventDefault();
    }
  });

  window.loadURL(MAIN_WINDOW_WEBPACK_ENTRY + "#/main_window");
//  window.webContents.openDevTools();
};

ipcMain.handle(
  "save-temp-audio-file",
  async (event, audioBuffer: ArrayBuffer) => {
    try {
      const tempFilePath = path.join(
        app.getPath("temp"),
        `temp_audio_${Date.now()}.wav`
      );
      fs.writeFileSync(tempFilePath, Buffer.from(audioBuffer));
      return tempFilePath;
    } catch (error) {
      throw error;
    }
  }
);

ipcMain.handle(
  "transcribe-audio-file",
  async (event, filePath: string, config) => {
    try {
      const formData = new FormData();
      formData.append("file", fs.createReadStream(filePath), "audio.wav");
      formData.append("model", "whisper-1");

      if (config.primaryLanguage && config.primaryLanguage !== "auto") {
        formData.append("language", config.primaryLanguage);
      }
      if (config.secondaryLanguage) {
        formData.append(
          "prompt",
          `This audio may contain ${config.primaryLanguage} and ${config.secondaryLanguage}.`
        );
      }

      const baseUrl = normalizeApiBaseUrl(config.api_base);
      const apiUrl = `${baseUrl}/audio/transcriptions`;
      const response = await axios.post(apiUrl, formData, {
        headers: {
          ...formData.getHeaders(),
          Authorization: `Bearer ${config.openai_key}`,
        },
        maxContentLength: Infinity,
        maxBodyLength: Infinity,
      });

      return response.data;
    } catch (error) {
      throw error;
    } finally {
      fs.unlinkSync(filePath);
    }
  }
);

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", async () => {
  createWindow();
  if (store.get("m5webhook_enabled")) {
    try {
      await startM5WebhookServer();
    } catch (err) {
      console.error("Failed to auto-start M5 webhook server:", err);
    }
  }
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the
// dock icon is clicked and there are no other windows open.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

import ElectronStore from "electron-store";
import { createServer, Server as HttpServer } from "http";
import { networkInterfaces } from "os";

interface StoreSchema {
  config: AppConfig;
  m5webhook_enabled?: boolean;
}

interface AppConfig {
  openai_key: string;
  api_base: string;
  gpt_model: string;
  api_call_method: "direct" | "proxy";
  primaryLanguage: string;
  secondaryLanguage: string;
  deepgram_api_key: string;
}

type TypedElectronStore = ElectronStore<StoreSchema> & {
  get: <K extends keyof StoreSchema>(key: K) => StoreSchema[K];
  set: <K extends keyof StoreSchema>(key: K, value: StoreSchema[K]) => void;
  clear: () => void;
};

// M5 Webhook Server Configuration
const M5_WEBHOOK_PORT = 7878;
const M5_WEBHOOK_HOST = "127.0.0.1";
const ALLOWED_M5_ACTIONS = ["start_recording", "ask_gpt", "clear_content", "clear_ai_result"];

let m5WebhookServer: HttpServer | null = null;
let mainWindow: BrowserWindow | null = null;

function validateM5Action(action: unknown): action is string {
  return typeof action === "string" && ALLOWED_M5_ACTIONS.includes(action);
}

function startM5WebhookServer(): Promise<void> {
  return new Promise((resolve, reject) => {
    if (m5WebhookServer) {
      console.log("M5 Webhook server already running");
      resolve();
      return;
    }

    m5WebhookServer = createServer((req, res) => {
      if (req.method === "POST" && req.url === "/webhook") {
        let body = "";
        req.on("data", (chunk) => {
          body += chunk.toString();
        });

        req.on("end", () => {
          try {
            const payload = JSON.parse(body);
            if (!validateM5Action(payload.action)) {
              res.writeHead(400, { "Content-Type": "application/json" });
              res.end(JSON.stringify({ error: "Invalid action" }));
              return;
            }

            if (mainWindow) {
              mainWindow.webContents.send("m5-action", payload.action);
            }

            res.writeHead(200, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ success: true }));
          } catch (err) {
            res.writeHead(400, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ error: "Invalid JSON" }));
          }
        });
      } else {
        res.writeHead(404, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: "Not found" }));
      }
    });

    m5WebhookServer.listen(M5_WEBHOOK_PORT, M5_WEBHOOK_HOST, () => {
      console.log(`M5 Webhook server listening on ${M5_WEBHOOK_HOST}:${M5_WEBHOOK_PORT}`);
      resolve();
    });

    m5WebhookServer.on("error", (err) => {
      console.error("M5 Webhook server error:", err);
      m5WebhookServer = null;
      reject(err);
    });
  });
}

function stopM5WebhookServer(): Promise<void> {
  return new Promise((resolve) => {
    if (m5WebhookServer) {
      m5WebhookServer.close(() => {
        console.log("M5 Webhook server stopped");
        m5WebhookServer = null;
        resolve();
      });
    } else {
      resolve();
    }
  });
}

function getLocalIP(): string {
  const interfaces = networkInterfaces();
  for (const name of Object.keys(interfaces)) {
    for (const iface of interfaces[name] || []) {
      if (iface.family === "IPv4" && !iface.internal) {
        return iface.address;
      }
    }
  }
  return "127.0.0.1";
}

const store = new ElectronStore<StoreSchema>() as TypedElectronStore;

function toSafeString(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

function sanitizeConfig(config: unknown): AppConfig {
  const source =
    config && typeof config === "object"
      ? (config as Record<string, unknown>)
      : {};
  const apiCallMethod =
    source.api_call_method === "proxy" ? "proxy" : "direct";

  return {
    openai_key: toSafeString(source.openai_key),
    api_base: toSafeString(source.api_base),
    gpt_model: toSafeString(source.gpt_model) || "gpt-4o",
    api_call_method: apiCallMethod,
    primaryLanguage: toSafeString(source.primaryLanguage) || "auto",
    secondaryLanguage: toSafeString(source.secondaryLanguage),
    deepgram_api_key: toSafeString(source.deepgram_api_key),
  };
}

const DEFAULT_API_BASE_URL = "https://api.openai.com/v1";
const ALLOWED_HTTP_HOSTS = new Set(["localhost", "127.0.0.1", "::1"]);

ipcMain.handle("get-config", () => {
  return sanitizeConfig(store.get("config"));
});

ipcMain.handle("set-config", (event, config) => {
  store.set("config", sanitizeConfig(config));
});

ipcMain.handle("m5webhook-start", async () => {
  try {
    await startM5WebhookServer();
    store.set("m5webhook_enabled", true);
    return { success: true };
  } catch (error) {
    return { success: false, error: error instanceof Error ? error.message : "Unknown error" };
  }
});

ipcMain.handle("m5webhook-stop", async () => {
  try {
    await stopM5WebhookServer();
    store.set("m5webhook_enabled", false);
    return { success: true };
  } catch (error) {
    return { success: false, error: error instanceof Error ? error.message : "Unknown error" };
  }
});

ipcMain.handle("m5webhook-get-status", () => {
  return {
    running: m5WebhookServer !== null,
    enabled: store.get("m5webhook_enabled") || false,
    host: M5_WEBHOOK_HOST,
    port: M5_WEBHOOK_PORT,
  };
});

ipcMain.handle("get-local-ip", () => {
  return getLocalIP();
});

ipcMain.handle("parsePDF", async (event, pdfBuffer) => {
  try {
    const pdf = require("pdf-parse");
    const data = await pdf(Buffer.from(pdfBuffer), {
      max: 0,
    });
    return { text: data.text };
  } catch (error) {
    return { error: "Failed to parse PDF: " + error.message };
  }
});

ipcMain.handle("process-image", async (event, imageData) => {
  try {
    const sharp = require("sharp");
    let image;
    if (imageData.startsWith("data:image")) {
      const base64Data = imageData.split(",")[1];
      const imageBuffer = Buffer.from(base64Data, "base64");
      image = sharp(imageBuffer);
    } else {
      throw new Error(
        "Invalid image input: expected Base64 encoded image data"
      );
    }
    const metadata = await image.metadata();
    return `Image size: ${metadata.width}x${metadata.height}, Format: ${metadata.format}`;
  } catch (error) {
    return { error: "Failed to process image: " + error.message };
  }
});

ipcMain.handle("highlightCode", async (event, code, language) => {
  return Prism.highlight(code, Prism.languages[language], language);
});

app.on("before-quit", async () => {
  await stopM5WebhookServer();
  const config = sanitizeConfig(store.get("config"));
  const apiInfo: AppConfig = {
    ...config,
    primaryLanguage: config.primaryLanguage || "en",
  };
  store.clear();
  store.set("config", apiInfo);
  const m5WebhookEnabled = store.get("m5webhook_enabled");
  if (m5WebhookEnabled) {
    store.set("m5webhook_enabled", m5WebhookEnabled);
  }
});

ipcMain.handle("get-system-audio-stream", async () => {
  try {
    const sources = await desktopCapturer.getSources({
      types: ["window", "screen"],
      fetchWindowIcons: false,
    });
    const audioSources = sources.filter(
      (source) =>
        source.name.toLowerCase().includes("sound") ||
        source.name.toLowerCase().includes("audio")
    );
    return audioSources.map((source) => source.id);
  } catch (error) {
    throw error;
  }
});

app.on("ready", () => {
  session.defaultSession.setDisplayMediaRequestHandler(
    (request, callback) => {
      desktopCapturer.getSources({ types: ["screen"] }).then((sources) => {
        callback({ video: sources[0], audio: "loopback" });
      });
    },
    { useSystemPicker: true }
  );

  ipcMain.handle(
    "transcribe-audio",
    async (event, audioBuffer: ArrayBuffer, config) => {
      try {
        const tempFilePath = path.join(
          app.getPath("temp"),
          `temp_audio_${Date.now()}.wav`
        );
        fs.writeFileSync(tempFilePath, Buffer.from(audioBuffer));

        const formData = new FormData();
        formData.append("file", fs.createReadStream(tempFilePath), {
          filename: "audio.wav",
          contentType: "audio/wav",
        });
        formData.append("model", "whisper-1");

        if (config.primaryLanguage && config.primaryLanguage !== "auto") {
          formData.append("language", config.primaryLanguage);
        }
        if (config.secondaryLanguage) {
          formData.append(
            "prompt",
            `This audio may contain ${config.primaryLanguage} and ${config.secondaryLanguage}.`
          );
        }

        const baseUrl = normalizeApiBaseUrl(config.api_base);
        const apiUrl = `${baseUrl}/audio/transcriptions`;
        const response = await axios.post(apiUrl, formData, {
          headers: {
            ...formData.getHeaders(),
            Authorization: `Bearer ${config.openai_key}`,
          },
          maxContentLength: Infinity,
          maxBodyLength: Infinity,
        });

        fs.unlinkSync(tempFilePath);

        return response.data;
      } catch (error) {
        throw error;
      }
    }
  );
});

ipcMain.handle("test-api-config", async (event, config) => {
  try {
    const axiosInstance = axios.create({
      baseURL: normalizeApiBaseUrl(config.api_base),
      headers: {
        Authorization: `Bearer ${config.openai_key}`,
        "Content-Type": "application/json",
      },
    });

    const response = await axiosInstance.post("/chat/completions", {
      model: config.gpt_model || "gpt-3.5-turbo",
      messages: [{ role: "user", content: "Hello, this is a test." }],
    });

    if (
      response.data.choices &&
      response.data.choices[0] &&
      response.data.choices[0].message
    ) {
      return { success: true };
    } else {
      return { success: false, error: "Unexpected API response structure" };
    }
  } catch (error) {
    if (axios.isAxiosError(error)) {
      if (error.response) {
        return {
          success: false,
          error: `Server responded with error: ${error.response.status} ${error.response.statusText}`,
        };
      } else if (error.request) {
        return {
          success: false,
          error:
            "No response received from server. Please check your network connection and API base URL.",
        };
      } else {
        return {
          success: false,
          error: `Error setting up the request: ${error.message}`,
        };
      }
    }
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error occurred",
    };
  }
});

ipcMain.handle("callOpenAI", async (event, { config, messages, signal }) => {
  try {
    const openai = new OpenAI({
      apiKey: config.openai_key,
      baseURL: normalizeApiBaseUrl(config.api_base),
    });

    const abortController = new AbortController();
    if (signal) {
      signal.addEventListener('abort', () => abortController.abort());
    }

    const response = await openai.chat.completions.create({
      model: config.gpt_model || "gpt-3.5-turbo",
      messages: messages,
    }, { signal: abortController.signal });

    if (
      !response.choices ||
      !response.choices[0] ||
      !response.choices[0].message
    ) {
      throw new Error("Unexpected API response structure");
    }
    return { content: response.choices[0].message.content };
  } catch (error) {
    if (error.name === "AbortError") {
      return { error: "AbortError" };
    }
    return { error: error.message || "Unknown error occurred" };
  }
});

ipcMain.handle("get-desktop-sources", async () => {
  try {
    const sources = await desktopCapturer.getSources({
      types: ["window", "screen"],
    });
    return sources.map((source) => ({
      id: source.id,
      name: source.name,
      thumbnail: source.thumbnail.toDataURL(),
    }));
  } catch (error) {
    return [];
  }
});

function normalizeApiBaseUrl(url: string): string {
  if (!url) return DEFAULT_API_BASE_URL;
  const normalizedInput = url.trim();
  const urlWithProtocol = /^https?:\/\//i.test(normalizedInput)
    ? normalizedInput
    : `https://${normalizedInput}`;
  const parsedUrl = new URL(urlWithProtocol);
  const isLocalHttp =
    parsedUrl.protocol === "http:" && ALLOWED_HTTP_HOSTS.has(parsedUrl.hostname);

  if (parsedUrl.protocol !== "https:" && !isLocalHttp) {
    throw new Error("Only HTTPS API URLs are allowed. HTTP is only allowed for localhost.");
  }

  const pathWithoutTrailingSlash = parsedUrl.pathname.replace(/\/+$/, "");
  if (!pathWithoutTrailingSlash || pathWithoutTrailingSlash === "/") {
    parsedUrl.pathname = "/v1";
  } else if (!pathWithoutTrailingSlash.endsWith("/v1")) {
    parsedUrl.pathname = `${pathWithoutTrailingSlash}/v1`;
  } else {
    parsedUrl.pathname = pathWithoutTrailingSlash;
  }
  parsedUrl.search = "";
  parsedUrl.hash = "";
  return `${parsedUrl.origin}${parsedUrl.pathname}`;
}

let deepgramConnection: any = null;

ipcMain.handle("start-deepgram", async (event, config) => {
  try {
    if (!config.deepgram_key) {
      throw new Error("Deepgram API key is missing");
    }
    const primaryLanguage = toSafeString(config.primaryLanguage);
    const deepgram = createClient(config.deepgram_key);
    deepgramConnection = deepgram.listen.live({
      punctuate: true,
      interim_results: true,
      model: "general",
      encoding: "linear16",
      sample_rate: 16000,
      endpointing: 300,
      ...(primaryLanguage && primaryLanguage !== "auto"
        ? { language: primaryLanguage }
        : {}),
    });

    deepgramConnection.addListener(LiveTranscriptionEvents.Open, () => {
      event.sender.send("deepgram-status", { status: "open" });
    });

    deepgramConnection.addListener(LiveTranscriptionEvents.Close, () => {
      event.sender.send("deepgram-status", { status: "closed" });
    });

    deepgramConnection.addListener(
      LiveTranscriptionEvents.Transcript,
      (data: any) => {
        if (
          data &&
          data.channel &&
          data.channel.alternatives &&
          data.channel.alternatives[0]
        ) {
          const transcript = data.channel.alternatives[0].transcript;
          if (transcript) {
            event.sender.send("deepgram-transcript", {
              transcript,
              is_final: Boolean(data.is_final),
            });
          }
        }
      }
    );

    deepgramConnection.addListener(
      LiveTranscriptionEvents.Error,
      (err: any) => {
        event.sender.send("deepgram-error", err);
      }
    );

    await new Promise((resolve, reject) => {
      deepgramConnection.addListener(LiveTranscriptionEvents.Open, resolve);
      deepgramConnection.addListener(LiveTranscriptionEvents.Error, reject);
      setTimeout(() => reject(new Error("Deepgram timeout")), 10000);
    });

    return { success: true };
  } catch (error) {
    return { success: false, error: error.message };
  }
});

ipcMain.handle("send-audio-to-deepgram", async (event, audioData) => {
  if (deepgramConnection) {
    try {
      const buffer = Buffer.from(audioData);
      deepgramConnection.send(buffer);
    } catch (error) {
      console.error("failed send data to Deepgram :", error);
    }
  }
});

ipcMain.handle("stop-deepgram", () => {
  if (deepgramConnection) {
    deepgramConnection.finish();
    deepgramConnection = null;
  }
});
